name: pg-rules-testbed

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: test_database
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
